### ISSUE TITLE
TASK [solr : Download] ********************************************************* fatal: [ubuntu]: FAILED! => {"changed": false, "failed": true, "msg": "unknown url type: /

### ISSUE THREAD

**Issue by dimthe** [phansible/role-solr#1]
Hi
it craps out at this point . I edited the solr versions up to 6.2.0 and 6.2.1
it still does not watnt to download , it gives this error

TASK [solr : Download] *********************************************************
fatal: [ubuntu]: FAILED! => {"changed": false, "failed": true, "msg": "unknown url type: /solr-6.2.0.tgz"}

any ideas please?

**Comment by dimthe** [comment]
Hello
At first i used the bundle roles from phansible to build solrcloud. Although the role starts fine it craps out at the above error. I checked the main.yml and it was set to download from the closest mirror. For some reason this never worked , at least for me . It was always giving the same error no matter how many solr versions i tried. 
I then came on here and i saw that this .yml was edited to : get_url: url="{{ solr_url }}/{{ solr_filename }}{{ solr_filename_extension }}" dest="/tmp/{{ solr_filename }}{{ solr_filename_extension }}

this worked and it downloaded solr but with problems.

first of all , when it sets up zookeeper it craps out saying zookeepr is not a system service or something similar to that , i can't remember the error now. Because i do not really need zookeeper ( i have seen solrclouds installations without zookeeper ) i went ahead and commented it out  from the all.yml and re run the role again. THis time everything worked during the playbook install.
When everything was finished i opened a browser from another computer and pointed it to the solr installation like this  http://192.168.1.77:8983/solr/. Then i get this error;  HTTP ERROR 500

Problem accessing /solr/. Reason:

```
Server Error
```

Caused by:

org.apache.solr.common.SolrException: Error processing the request. CoreContainer is either not initialized or shutting down.       with many more error lines 

at this point i have no idea what is wrong with it how to fix this and how to continue.
Can you help please ?

@debo

**Comment by dimthe** [comment]
ok update

i think i found a way to keep this going. I had to /opt/solr/bin$ sudo ./solr start -e cloud  and follow the steps there to build a cloud.  seems to be ok for now 

my question now is this :  can the " start -e cloud " along with the questions it asks you be implemented in the solrcloud playbook so you just run the role and it builds everything for you?  thanks again   @debo

**Comment by dimthe** [comment]
and after all this success , here is the first error 
i am following the how tos from apache's page ..

:/opt/solr$ bin/post -c hometest docs/
/home/dimtheo/jdk/jdk1.7.0_60/bin/java -classpath /opt/solr/dist/solr-core-6.2.0.jar -Dauto=yes -Dc=hometest -Ddata=files -Drecursive=yes org.apache.solr.util.SimplePostTool docs/
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/solr/util/SimplePostTool : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by debo** [comment]
Hi @dimthe thanks for all the precious inputs, I will have a look at this as soon as I can taking in consideration all your discoveries.

**Comment by dimthe** [comment]
Hi 
so the role is now working 100 % , tested on a fresh Ubuntu Virtual machine

the whole solrcoud instances took 8min to build . As a bonus i wrote a simple script to execute all the manual solr commands to build the cloud  and i call it via ansible at the end of the playbook . The commands are found on apache's page . They are easy to understand 
so when you can @debo test this yourself

thanks again

**Comment by debo** [comment]
@dimthe I'll definitely will especially now that I am actively back 😄

**Comment by dimthe** [comment]
good to know @debo  :)
